name: big-bear-portainer
services:
  app:
    image: portainer/portainer-ce:2.20.0-alpine
    container_name: big-bear-portainer
    hostname: big-bear-portainer
    network_mode: bridge
    privileged: true
    ports:
    - 8000:8000
    - 9000:9000
    - 9443:9443
    volumes:
    - /DATA/AppData/big-bear-portainer/data:/data
    - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: '268435456'
    cpu_shares: 90
    labels:
      icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/portainer-alt.png?raw=true
